// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dims_cpp
List dims_cpp(List lst);
RcppExport SEXP _ijtiff_dims_cpp(SEXP lstSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type lst(lstSEXP);
    rcpp_result_gen = Rcpp::wrap(dims_cpp(lst));
    return rcpp_result_gen;
END_RCPP
}
// float_max
double float_max();
RcppExport SEXP _ijtiff_float_max() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(float_max());
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP read_tif_c(SEXP);
RcppExport SEXP write_tif_c(SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_ijtiff_dims_cpp", (DL_FUNC) &_ijtiff_dims_cpp, 1},
    {"_ijtiff_float_max", (DL_FUNC) &_ijtiff_float_max, 0},
    {"read_tif_c",        (DL_FUNC) &read_tif_c,        1},
    {"write_tif_c",       (DL_FUNC) &write_tif_c,       5},
    {NULL, NULL, 0}
};

RcppExport void R_init_ijtiff(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
