// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dims_cpp
List dims_cpp(List lst);
RcppExport SEXP _ijtiff_dims_cpp(SEXP lstSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type lst(lstSEXP);
    rcpp_result_gen = Rcpp::wrap(dims_cpp(lst));
    return rcpp_result_gen;
END_RCPP
}
// float_max
double float_max();
RcppExport SEXP _ijtiff_float_max() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(float_max());
    return rcpp_result_gen;
END_RCPP
}
