# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dims_cpp <- function(lst) {
    .Call('_ijtiff_dims_cpp', PACKAGE = 'ijtiff', lst)
}

float_max <- function() {
    .Call('_ijtiff_float_max', PACKAGE = 'ijtiff')
}

